[build]
  command = "NITRO_PRESET=netlify npm run build"
  publish = ".output/public"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../package-lock.json"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 