[build]
  command = "npm ci && npm run generate"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 